### ISSUE TITLE
[Tracking Issue] Create parser

### ISSUE THREAD

**Issue by DragonAxe** [DragonAxe/CSE423-Compiler-Collective#22]
Your project will recognize and represent a subset of the C language. The following language
features are required:

- [ ] Identifiers, variables, functions
- [ ] Keywords
- [ ] Arithmetic expressions
- [ ] Assignment
- [ ] Boolean expressions
- [ ] Goto statements
- [ ] If / Else control flow
- [ ] Unary operators
- [ ] Return statements
- [ ] Break statements
- [ ] While loops

The following language features are optional:

- [ ] Types other than integers
- [ ] ++, —, -=, +=, *=, /=
- [ ] For loops
- [ ] Binary operators
- [ ] Switch statements

The following language features are not expected, although may be attempted:

- [ ] Pointers, arrays, strings
- [ ] Preprocessor statements
- [ ] Struct, enum
- [ ] Casting, type promotion
- [ ] Type specs

Your program should:

- [ ] Gracefully handle any input without crashing.
- [ ] For an invalid file, return a reasonable error message.
