### ISSUE TITLE
[Tracking Issue] Documentation for assignment 1

### ISSUE THREAD

**Issue by DragonAxe** [DragonAxe/CSE423-Compiler-Collective#23]
The deliverable should include a document describing the specification and design of the
program, along with a user guide.
Please include the following sections at a minimum:

- [ ] Program Overview
- [ ] Usage
- [ ] Design discussion with limitations and tradeoffs
- [ ] Language specification - what do you and don’t you recognize

In addition,

- [ ] code should be commented reasonably (not excessively),
- [ ] including a comment for each function,
- [ ] and in-function comments for any part of the code that needs additional explanation.

Related issue: #20 Add group names to design document
